name: Integration Tests
on:
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dashboard/test/run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker environment
        run: |
          docker-compose up -d db stripe

      - name: Build and run the app
        run: |
          docker-compose run app bash -c "yarn install --frozen-lockfile && npx prisma migrate deploy && yarn vitest run"
